update controller-gen
devfile/registry-operator pull request #33
Opened 2023-02-10 17:36 UTC by kim-tsao

Signed-off-by: Kim Tsao <ktsao@redhat.com>

**Please specify the area for this PR**

**What does does this PR do / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #?
https://github.com/devfile/api/issues/1013

In addition to the changes mentioned in this [comment](https://github.com/devfile/api/issues/1013#issuecomment-1416085552), I had to update the controller-manager and kube-rbac-proxy sccs in order to fix the warning on openshift:

`Warning: would violate PodSecurity "restricted:v1.24": allowPrivilegeEscalation != false (container "kube-rbac-proxy" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (containers "kube-rbac-proxy", "manager" must set securityContext.capabilities.drop=["ALL"]), seccompProfile (pod or containers "kube-rbac-proxy", "manager" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")`

**PR acceptance criteria**:

- [ ] Test Coverage 
    - Are your changes sufficiently tested, and are any applicable test cases added or updated to cover your changes?
- [ ] Gosec scans 
  - Fix all MEDIUM and higher findings and/or annotate a finding per gosec instructions: https://github.com/securego/gosec#annotating-code to address why a finding is not a security issue

Documentation
- [ ] Does the [registry operator documentation](https://github.com/devfile/devfile-web/tree/main/libs/docs/src/docs/no-version) need to updated with your changes?

**How to test changes / Special notes to the reviewer**:

2023-02-10 18:48 UTC, michael-valdron commented
`go mod tidy: go.mod file indicates go 1.18, but maximum supported version is 1.17` our integration tests need updating to support golang 1.18, we could cap it at 1.17 until this support is added.

2023-02-10 18:55 UTC, michael-valdron requested changes
Aside from my suggestions there might be other changes needed to stay at golang 1.17.

2023-02-10 18:55 UTC, michael-valdron commented on Dockerfile
> +FROM golang:1.18 as builder
```suggestion
FROM golang:1.17 as builder
```
> `go mod tidy: go.mod file indicates go 1.18, but maximum supported version is 1.17` our integration tests need updating to support golang 1.18, we could cap it at 1.17 until this support is added.

Keep it at 1.17 for now.

2023-02-10 18:55 UTC, michael-valdron commented on go.mod
> +go 1.18
```suggestion
go 1.17
```
> `go mod tidy: go.mod file indicates go 1.18, but maximum supported version is 1.17` our integration tests need updating to support golang 1.18, we could cap it at 1.17 until this support is added.

Update it to golang 1.17 instead for now.

2023-02-10 19:30 UTC, michael-valdron approved these changes
> `go mod tidy: go.mod file indicates go 1.18, but maximum supported version is 1.17` our integration tests need updating to support golang 1.18, we could cap it at 1.17 until this support is added.

/lgtm

I see your changes for testing support https://github.com/openshift/release/pull/36276 you can disregard my review suggestions.

2023-02-10 19:38 UTC, kim-tsao commented
/retest

2023-02-10 19:42 UTC, michael-valdron approved these changes
/lgtm

2023-02-14 16:25 UTC, kim-tsao commented
/retest

2023-02-14 21:03 UTC, kim-tsao commented
/retest

2023-02-17 17:26 UTC, kim-tsao commented
Also updated a couple of dependencies related to upgrading the operator-sdk: https://sdk.operatorframework.io/docs/upgrading-sdk-version/v1.25.0/

2023-02-17 18:42 UTC, merged