Updates for operator sdk v1.28
devfile/registry-operator pull request #45
Opened 2023-08-24 18:14 UTC by michael-valdron

**Please specify the area for this PR**

**What does does this PR do / why we need it**:

Provides updates to the project files to support Operator SDK version 1.28, these changes are documented under https://sdk.operatorframework.io/docs/upgrading-sdk-version/ up to [v1.28 docs](https://sdk.operatorframework.io/docs/upgrading-sdk-version/v1.28.0/).

**Which issue(s) this PR fixes**:

Fixes #?

fixes devfile/api#1106

**PR acceptance criteria**:

- [ ] Test Coverage 
    - Are your changes sufficiently tested, and are any applicable test cases added or updated to cover your changes?
- [ ] Gosec scans 
  - Fix all MEDIUM and higher findings and/or annotate a finding per gosec instructions: https://github.com/securego/gosec#annotating-code to address why a finding is not a security issue

Documentation
- [ ] Does the [registry operator documentation](https://github.com/devfile/devfile-web/tree/main/libs/docs/src/docs/no-version) need to updated with your changes?

**How to test changes / Special notes to the reviewer**:

2023-08-28 16:24 UTC, johnmcollier requested changes
Left some comments.

Also, could we move back the controller go sources from `internal/controller/xyz` to just `controllers/`? I think `internal/controller` is the default for new controller runtime projects, but the added "internal" in the path is unnecessary for our use case IMO

2023-08-28 16:24 UTC, johnmcollier commented on config/rbac/service_account.yaml
> +  name: sa
Nit: `service-account` might be preferable to `sa` here.

2023-08-28 16:58 UTC, michael-valdron commented
> @michael-valdron: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> Test name 	Commit 	Details 	Required 	Rerun command
> ci/prow/v4.12-registry-operator-integration-test 	[1f0abf2](https://github.com/devfile/registry-operator/commit/1f0abf227101dd4cbada1fcd7559c46298c08477) 	[link](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/devfile_registry-operator/45/pull-ci-devfile-registry-operator-main-v4.12-registry-operator-integration-test/1696183645716353024) 	true 	`/test v4.12-registry-operator-integration-test`
> 
> [Full PR test history](https://prow.ci.openshift.org/pr-history?org=devfile&repo=registry-operator&pr=45). [Your PR dashboard](https://prow.ci.openshift.org/pr?query=is:pr+state:open+author:michael-valdron).

CI is still running the integration tests using `go 1.18`, this needs to be updated to `go 1.19` for this to pass.

```
go: go.mod file indicates go 1.19, but maximum version supported by tidy is 1.18
```

2023-08-28 17:00 UTC, michael-valdron commented on CHANGELOG.md
> +# Change Log
Yeah this was my thought too, at the moment its expecting manual entry but its something we should automate going forward. I can add this as an acceptance criteria for PRs until we do.

2023-08-28 18:10 UTC, michael-valdron commented on CHANGELOG.md
> +# Change Log
Done: https://github.com/michael-valdron/devfile-registry-operator/blob/ff1108401205cdc55eb69b3506f80d26706301dd/.github/PULL_REQUEST_TEMPLATE.md?plain=1#L11

2023-08-28 18:10 UTC, michael-valdron commented
> Left some comments.
> 
> Also, could we move back the controller go sources from `internal/controller/xyz` to just `controllers/`? I think `internal/controller` is the default for new controller runtime projects, but the added "internal" in the path is unnecessary for our use case IMO

Reverted go v4 project structure changes.

2023-08-29 14:58 UTC, michael-valdron commented
/retest

2023-08-29 14:59 UTC, michael-valdron commented
/retest-all

2023-08-29 16:11 UTC, michael-valdron commented
/retest-required

2023-08-30 03:17 UTC, michael-valdron commented
/retest

2023-08-30 18:10 UTC, michael-valdron commented
/retest

2023-08-30 19:36 UTC, michael-valdron commented
/test

2023-08-30 19:36 UTC, michael-valdron commented
/test all

2023-08-30 20:04 UTC, michael-valdron commented
/retest

2023-08-30 23:20 UTC, michael-valdron commented
/retest

2023-08-30 23:56 UTC, johnmcollier commented
/retest

2023-08-30 23:56 UTC, johnmcollier approved these changes

2023-08-31 13:19 UTC, michael-valdron commented
/retest

2023-08-31 15:22 UTC, johnmcollier approved these changes
/lgtm

2023-08-31 15:27 UTC, merged